import arcade

TITLE = "SOBOKAN"
FIELD_WIDTH = 30;
FIELD_HEIGHT = 30;
BOARD_SIZE = [10, 10]
WINDOW_WIDTH = BOARD_SIZE[0] * FIELD_WIDTH
WINDOW_HEIGHT = BOARD_SIZE[0] * FIELD_HEIGHT
BACKGROUND_COLOR = arcade.color.WHITE
