import arcade

TITLE = "SOKOBAN"
PATH_TO_LEVELS = 'levels/'
PATH_TO_MANUAL_GAMES = 'manual_games/'
DEFAULT_LEVEL = "simple_level_3.txt"

MOVE_TIMEOUT = 200

MOVE_TIME_OFFSET = 1
FINISH_GAME_STOP_TIME = 3
INPUT_MOVES_DELIMITER = ";"

FIELD_WIDTH = 30
FIELD_HEIGHT = 30
BOARD_SIZE = [10, 10]
WINDOW_WIDTH = 600#int
WINDOW_HEIGHT = 600#int
BACKGROUND_COLOR = arcade.color.WHITE

# RecordSaver
OUT_FILE_EXTENSION = '.txt'
RECORD_DELIMITER = ";"

