import arcade

TITLE = "SOKOBAN"
PATH_TO_LEVELS = 'levels/'
PATH_TO_MANUAL_GAMES = 'manual_games/'
DEFAULT_LEVEL = "simple_level_3.txt"

MOVE_TIMEOUT = 200

TIME_OFFSET = 0.3
INPUT_MOVES_DELIMITER = ";"

FIELD_WIDTH = 30
FIELD_HEIGHT = 30
BOARD_SIZE = [10, 10]
WINDOW_WIDTH = int
WINDOW_HEIGHT = int
BACKGROUND_COLOR = arcade.color.WHITE

# RecordSaver
OUT_FILE_EXTENSION = '.txt'
RECORD_DELIMITER = ";"

