MAP_WIDTH = 20
MAP_HEIGHT = 20
NUM_OF_CHESTS = 1
NUM_OF_MOVES = 20

# PROB_OF_PULLING_STRAIGHT_FORWARD = 0.75
# PROB_OF_CHANGING_SIDE = 0.5
# PROB_OF_GOING_TO_ANOTHER_CHEST = 0.01

PATH_TO_MAPS = 'generated_maps/'
